Add reports and leaderboard, and remove PHP
bitshares/hackthedex.io pull request #1
Opened 2019-02-08 12:59 UTC by sschiessl-bcp

@mattbeckman

How do I link the reports properly?

@ryanRfox 

Please approve the content of the reports

2019-02-10 16:40 UTC, mattbeckman commented
Linking to the full path is fine if you stick with PDFs (e.g. /src/assets/reports/Report123.pdf).

2019-02-11 13:14 UTC, ryanRfox requested changes
I am happy with the PDF content. I would prefer MD to enable easier collaboration during drafting and standardized in-browser rendering. 

I have one request below related to labeling the rewards.

2019-02-11 13:14 UTC, ryanRfox commented on src/view-models/leaderboard.js
> +			totalReward: 17333
Please add " bitUSD" to this reward and on line 18 as well. Future remittance will (likely) be in bitCNY, so prefer not to add the label into the column heading.

2019-02-11 15:14 UTC, sschiessl-bcp commented
> I am happy with the PDF content. I would prefer MD to enable easier collaboration during drafting and standardized in-browser rendering.

I will look into this for next report and eventually change the old ones.

2019-02-11 15:14 UTC, sschiessl-bcp commented
@mattbeckman please merge

2019-02-11 16:50 UTC, ryanRfox approved these changes

2019-02-11 16:52 UTC, ryanRfox commented
Yes. I made my Review approval. (FYI - I do not have write access; which is just fine).

2019-02-11 17:19 UTC, merged